// app/yoga_5min/lessons.ts
export const lessons = [
    { slug: "lesson-1",  
      title: "Lesson 1",  
      videoId: "3Cw_npFF54U", 
      image: "/lessons_example/lesson-1.png",
      apiTarget: "warrior-ii", 
    },
    { slug: "lesson-2",  
      title: "Lesson 2",  
      videoId: "3Cw_npFF54U", 
      image: "/lessons_example/lesson-2.png",
      apiTarget: "accomplished", 
    },
    { slug: "lesson-3",  
      title: "Lesson 3",  
      videoId: "3Cw_npFF54U", 
      image: "/lessons_example/lesson-3.png",
      apiTarget: "fire-log", 
    },
    { slug: "lesson-4",  
      title: "Lesson 4",  
      videoId: "3Cw_npFF54U", 
      image: "/lessons_example/lesson-4.png",
      apiTarget: "goddess", 
    },
    { slug: "lesson-5",  
      title: "Lesson 5",  
      videoId: "3Cw_npFF54U", 
      image: "/lessons_example/lesson-5.png",
      apiTarget: "hovering-bird-dog", 
    },
    { slug: "lesson-6",  
      title: "Lesson 6",  
      videoId: "3Cw_npFF54U", 
      image: "/lessons_example/lesson-6.png",
      apiTarget: "mountain", 
    },
    { slug: "lesson-7",  
      title: "Lesson 7",  
      videoId: "3Cw_npFF54U", 
      image: "/lessons_example/lesson-7.png",
      apiTarget: "tree", 
    },
] as const;

export const findBySlug = (slug: string) =>
    lessons.find(l => l.slug === slug);
