// app/yoga_5min/lessons.ts
export const lessons = [
    { slug: "lesson-1",  
      title: "Lesson 1",  
      videoId: "wMjf2_zE37c", 
      image: "/lessons_example/lesson-1.png",
      apiTarget: "warrior-ii", 
      displayTitle: "戰士二式",
    },
    { slug: "lesson-2",  
      title: "Lesson 2",  
      videoId: "74t3vtW4-OQ", 
      image: "/lessons_example/lesson-2.png",
      apiTarget: "accomplished", 
      displayTitle: "安坐式",
    },
    { slug: "lesson-3",  
      title: "Lesson 3",  
      videoId: "3yxRGcrypa0", 
      image: "/lessons_example/lesson-3.png",
      apiTarget: "fire-log", 
      displayTitle: "火木樁式",
    },
    { slug: "lesson-4",  
      title: "Lesson 4",  
      videoId: "NycwXXw5IPg", 
      image: "/lessons_example/lesson-4.png",
      apiTarget: "goddess", 
      displayTitle: "女神式",
    },
    { slug: "lesson-5",  
      title: "Lesson 5",  
      videoId: "aAbjg7OcoAE", 
      image: "/lessons_example/lesson-5.png",
      apiTarget: "bird-dog", 
      displayTitle: "鳥狗式",
    },
    { slug: "lesson-6",  
      title: "Lesson 6",  
      videoId: "1tU_6vvnoCo", 
      image: "/lessons_example/lesson-6.png",
      apiTarget: "mountain", 
      displayTitle: "山式", 
    },
    { slug: "lesson-7",  
      title: "Lesson 7",  
      videoId: "o3NPdT_O-tg", 
      image: "/lessons_example/lesson-7.png",
      apiTarget: "tree", 
      displayTitle: "樹式",
    },
] as const;

export const findBySlug = (slug: string) =>
    lessons.find(l => l.slug === slug);
