// app/yoga_5min/lessons.ts
export const lessons = [
  { slug: "lesson-1",  
    title: "戰士二式",  
    videoId: "wMjf2_zE37c", 
    image: "/lessons_example/lesson-1.png",
    apiTarget: "warrior-ii", 
  },
  { slug: "lesson-2",  
    title: "達人坐姿",  
    videoId: "74t3vtW4-OQ", 
    image: "/lessons_example/lesson-2.png",
    apiTarget: "accomplished", 
  },
  { slug: "lesson-3",  
    title: "雙腿交疊式",  
    videoId: "3yxRGcrypa0", 
    image: "/lessons_example/lesson-3.png",
    apiTarget: "fire-log", 
  },
  { slug: "lesson-4",  
    title: "女神式",  
    videoId: "NycwXXw5IPg", 
    image: "/lessons_example/lesson-4.png",
    apiTarget: "goddess", 
  },
  { slug: "lesson-5",  
    title: "鳥狗式",  
    videoId: "aAbjg7OcoAE", 
    image: "/lessons_example/lesson-5.png",
    apiTarget: "bird-dog", 
  },
  { slug: "lesson-6",  
    title: "山式",  
    videoId: "1tU_6vvnoCo", 
    image: "/lessons_example/lesson-6.png",
    apiTarget: "mountain", 
  },
  { slug: "lesson-7",  
    title: "樹式",  
    videoId: "o3NPdT_O-tg", 
    image: "/lessons_example/lesson-7.png",
    apiTarget: "tree", 
  },
] as const;
export const findBySlug = (slug: string) =>
  lessons.find(l => l.slug === slug);